#pragma once

#include <glib.h>

/* wrap input to the given line_length. Each line is wrapped on the last
 * whitespace before reaching line_length.
 * 
 * If hyphons_if_wrap_impossible is TRUE, hyphons will be inserted if a line is
 * longer than line_length and has no whitespace to wrap on.
 * 
 * If hyphons_if_wrap_impossible is FALSE, lines longer than line_length will
 * only be wrapped if they contain whitespace.
 * 
 * Returns a GPtrArray, with (gchar *) pointers to each wrapped line, stored as
 * null-terminated character arrays
 */
GPtrArray *wrap_lines(const gchar *input, const gsize line_length, const gboolean hyphons_if_wrap_impossible);

/*
 * Completely frees the GPtrArray. Expects an array as generated by wrap_lines.
 *
 * Evey line will be freed, along with the pointer array itself.
 */
void free_wrapped_lines(GPtrArray *array);